// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_swsyUMOlcu6LZXyM9kLjwQelXDV1tg',
    appId: '1:847740221561:web:a578f4d6fe47006cd73ca8',
    messagingSenderId: '847740221561',
    projectId: 'spotify-f199a',
    authDomain: 'spotify-f199a.firebaseapp.com',
    storageBucket: 'spotify-f199a.appspot.com',
    measurementId: 'G-TGCMYQMK2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYtAU6moN11XTvR62YHPjEWt-ogSELgsA',
    appId: '1:847740221561:android:6dee2f94e4d4804dd73ca8',
    messagingSenderId: '847740221561',
    projectId: 'spotify-f199a',
    storageBucket: 'spotify-f199a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3ALnjP0VJqhVyyn5BZzWHQu82VPEaJg',
    appId: '1:847740221561:ios:929f96e3c33c9685d73ca8',
    messagingSenderId: '847740221561',
    projectId: 'spotify-f199a',
    storageBucket: 'spotify-f199a.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe3ALnjP0VJqhVyyn5BZzWHQu82VPEaJg',
    appId: '1:847740221561:ios:929f96e3c33c9685d73ca8',
    messagingSenderId: '847740221561',
    projectId: 'spotify-f199a',
    storageBucket: 'spotify-f199a.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_swsyUMOlcu6LZXyM9kLjwQelXDV1tg',
    appId: '1:847740221561:web:35743b80b3375776d73ca8',
    messagingSenderId: '847740221561',
    projectId: 'spotify-f199a',
    authDomain: 'spotify-f199a.firebaseapp.com',
    storageBucket: 'spotify-f199a.appspot.com',
    measurementId: 'G-BEQTK8RV00',
  );
}
